{% set version = "1.2-7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-fastica
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fastICA_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fastICA/fastICA_{{ version }}.tar.gz
  sha256: bcb76972e070e3892472b5d9163c280f1cca8df9deffecb4429144fdb50a9c21

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base                 # [build_platform != target_platform]
  host:
    - libblas
    - liblapack
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('fastICA')"           # [not win]
    - "\"%R%\" -e \"library('fastICA')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=fastICA
  license: GPL-2.0-or-later
  summary: Implementation of FastICA algorithm to perform Independent Component Analysis (ICA) and Projection Pursuit.
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: fastICA
# Version: 1.2-2
# Date: 2019-07-08
# Title: FastICA Algorithms to Perform ICA and Projection Pursuit
# Author: J L Marchini, C Heaton and B D Ripley <ripley@stats.ox.ac.uk>
# Maintainer: Brian Ripley <ripley@stats.ox.ac.uk>
# Depends: R (>= 3.0.0)
# Suggests: MASS
# Description: Implementation of FastICA algorithm to perform Independent Component Analysis (ICA) and Projection Pursuit.
# License: GPL-2 | GPL-3
# NeedsCompilation: yes
# Packaged: 2019-07-08 14:58:13 UTC; ripley
# Repository: CRAN
# Date/Publication: 2019-07-08 14:59:51 UTC
