travis:
  secure:
    BINSTAR_TOKEN: mFbmTpSKLibIEDYBEgXHediyd8SKKljnGvN1YJEymTYb1qRqH258xf16DnKxryMCXC9c6yZ572Yjfrr/7eeziT+9VYK9cI2fBTo1yOaCcgO71sYDU1o0mh36od2nYEiGrB/nlgxn17asoGI9CmHN8jxwajqjKossva7/fXXXDuf4joMxhqWkn8Xy7U4L84ZlX/MDYMR1QVJFGIcqTV7Z7tJ8ktigJ5oqsbYzRgmi1buO4fDi02DJBOQIxbItAD9mbh7XQS9iLdUUa3iAMk3n6ludhxXi1C9iOnOCUikxsESFSiYIjepKxNjEmBPzPiO88ebakEfp2KsB9YQbsEBdmrw6qoqxfq7jWjq4s8gvwyiB2Zt2mA1Od34bmNEmJnMJfrKIQv9aVJlIu90c8SrzTS6Sv7/00PuMy7L5hPE2CyYKe7AcuVIStP+9YRT6Lg3OBoGlsGeIbA0ExdI5wYZHCU8rIV4JV1pWQERWjYX3e1sim86s4SgRqvRtW/CQw9pl7NZonALEEIrh/+N8w4LM9qoYAyW0ZGczPtf0kuNUXdOl1OkZ1cKSxh+2wQuB8Gdv8K2o5NfMRgV3R8fvR+kZzojleJZucurQ8IGJItlya6v00nrygHFcQL14rBqTOlKMDzD8GroW9Qvcgisn5iQKkFzCRH1mE5hjV7BexrrMkfk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
