travis:
  secure:
    BINSTAR_TOKEN: MyOJh9vLFWrxeJLH8++077GsxAi5XClWK+Vb6YFCWWD2EXaAkiEIgQqtYo7ihXIG7Rv9WLhp8LRXgOJyVTUCKlbA2pktwSwpzHaTFKWYqR77VpMyECsyIz9n2xD7i72YQNLilYLRzR6QEShPi9TKsoNAns75OjyYSbSAKpzm/TqcNiIJTZdCHnnqNewOMTZYbtulT+C6g+r6dXIFMS4YdiitQTWimcbGA5nek7HdCuBVWi340aTUQ8Xoi87Cnv1tn+yqGD5RD3iVjHFjB76EbPehbuMSuBRwqxteH8bZ336Ha5XnA7GZxFN9PdwTB6xeAwqhwdeN0yaErPGXAvNtYFyfSu0zY2Rq7VcVtDIMDo6CAzMWn8eStWiz4Wb4+jxgAFxPZYFnFfKXqNiEwWE8DQ0cz+cOukkt4Yd58x/6SU5evIbql5c7JgJ0WXO8wPiFLaALVP+lkRZWnR4c6D36rc+TCUTbt+8IYvbLVyo3TLRp5BWQgYpKtZEhsnK8QuebqW49jVq54gRG06/vH11B9QztllnJ9N43vAF3EXt75bZ0mympPjt7uVjUW3UKpxyx/NLcpX7UkGxF0I0ibN2a7b5yoQ+2vXBM3EHNmc+XjWPL+iOJH5lcyxOXz+ykwAOwxxdfheUsl0X+Zbfu7qjpR/chthhZIzf8rIWzxk96Ma8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
