travis:
  secure:
    BINSTAR_TOKEN: i2OJOSo9YuCl1UxCEfk36nB2raz7Qzb4kSe3DQbBsjwFMVPFSj9lpAvrgv/puV/2LdpFxP8dWsXfIT2mBEpChSE+ug7WLIxKfiq0Vxg8jviCzRszK+cZkR10lxglJ+saQJJ6uq6xMfkfov9cwP5rDEADD6asUpP51pKh7rykdUU5UM+qEmIScs0U287rOTZ2YlbXZQUm9U194T8dAB1MAtOdq1ngoVSXeT1FZAE7K56HtydNIW2BcqhRniHlu6/F3nar4PIdlRHpj6ypTM9EBlosLudpFYAf1crPIdOstFiV13dTESfVy08j/YW83iCQgsQbQ+EnpxbFGp/QqBC2EIoMe3/yQ4d5WEMLaUWLC1vDjnmrpN1V07YG6z9YtY/r+mvvadWy9BgcVXTATMV5OszVSrRGUu96MgEkDoUe8nAL5WqZXorJQ+TDwawPatcj5PTFXST+mAUk6uRB/LfsVJYWQq8csh/8LdY9MrLzloku20kEo7krN9jcJFqJRq8e5IG6u3hXKaWCFk5GGW6thJJO8biVf+6o+1Mg6tw42eBT+PR30xqNy8k2va41RKnEO2oWEl4/eO/xLDhuhMUGe6acYGmZhEdYJ06UHH3JcAVWtyeVcWsFv/rxmfWNfjTEmHsmpKyCHffKqpKysPDjyljXJ0eNX8DofHa3YAeyLmQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
