travis:
  secure:
    BINSTAR_TOKEN: l1i4tCu1RNPitSvYJLSPv0lk81DPF1iDr85SK5MiFlu1c9dQBWjCqzy8OJozFtwuPQxtSvUiBq/Fj3oEpeyrFtHmXTsPCQ7xObFm+siLh1WFLOjHhQJkFSNtitq3htrtRDnAvfuirguJ5ZjnN7AIHYstsCB8YSu+Ipb8pHVbxqod0y9QX7tF75uSztlCwFd3YonckrUJukAvXDD9OLBfv1hdwSR68//h5f82p2G2Mym1/v1EPlHLqKCogqt3JqhWF6+b6rXwkBAhofvEX21tOCCVMdHxnTqhZcFAtC6gJ5MnzweIHHItVAU4Ois5OucgKAV13EOQ8bg8FKpdpRFZ9/6i+mH7RiN+VvbO4p/tXiPTnoIp4kG6C1rbf+/numbSNl/SjWHeri4qLori9v7i9IcUbudHoKpNvVHhUk5z38o2w08d25ArOKc1V94LtLIiFPgdrWJJRKLbijwIZJufnPCvVmlo9lX1++np53MjoNa/exFXEn2gydQ3IEWCRUDXnKo/AY1+8zMgleKCae7cKIWAVG7IUvE9T98/OXukTXb6uF+d7VRsUQKCBHWazHmVUcIj2GHKZ2zw7o9/4pIlhNVtXFmBdOvMXiXl+ywRajElzd+lgRTj95cONmcxs/93MAqqh+m7gZ+R2cxeNbyVwGNpmrK/Ocgfitgq+MCBXrA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
