appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: fDpsmHghczHKThLG06c6PDAbvXzw92jgzs1hsY6LG5momhXsBTbhT6OIz7+acXSp9xRGz8CL5DkzkBixiu9n0f4TIahgP0uDGGeYki+lJncOUU0M5YMorVo4xmeq9sX52688KY/GyHH4cM2sMbqMp/DfoqcIQtmsc4unk9Nx89iQcGlkMyISOJZZBwW+0wfqmX3h8VKoZdvs9PJLZ30vNx2NmByltAuiLJNt5MynbnT4ZlG0fCCwU1brhONigtDBM/Ff5EeI4bXcWIWVDR0HAa+6h8AxTuuDHpMvfm364+Sr2HhcqlAsBvI0vRMD0bxsctNFgvwORkiRh6nC/TluVZst+3f0Emk2Cr4h5Pa1j6Ga63hMQYmMsSm/xKEX5VV9ehwRBFIbsQR7GaRywbHiJq0tlKEUg8asfkOOtR3igqaBrvNDYRwoQP8Hu2ef8yRSeuwOyo10eLGuQZ/galBy0NhT1hy0JzWvdmzRMVLOfhkxVvy01atc2Jr7SmY3OFGqCZG1BawSov1jlFOFq/KrVsMtq3kDSnLF1L/54mZqHWRslh2xX/A1v2gXJueqmfN28R+vEE9HMOP7w6m24OIwniTBqcBH1iw/o9JUS37xaG15qhK8n81g9xqRUkeQfHFlj0SRM+oib04eBp/WkU0hjCZyiVLYLk0XsLVAnwfTQEw=
conda_forge_output_validation: true
